# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# - Added a cron schedule to run every week. This is particularly helpful
#   for the clippy step, since new releases of Rust tend to introduce
#   new warnings (which in this configuration are treated as errors).
#
# - Shortened name so that in the github summary UI you can see the job
#   names (otherwise they get cut off).
#
# - Add doc job.
#
# - Added rust-cache which speeds up rebuilds a lot.
#
# License: CC0, see https://github.com/actions-rs/meta/blob/HEAD/LICENSE

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo clippy -- -D warnings

  doc:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo doc
        env:
          RUSTDOCFLAGS: -Dwarnings
